version: 2.09.{build}

image:
- Visual Studio 2019
- Ubuntu1804

configuration:
- Release
platform:
- x64
shallow_clone: true

test: false

for:
- matrix:
    except:
    - image: Ubuntu1804
  build:
    project: TheDarkMod.sln
    parallel: true
    verbosity: minimal
  after_build:
  - cmd: |
      7z a -tzip tdm_vr.pk4 ..\darkmod\glprogs_vr
      7z a -t7z TheDarkModVR.7z ..\darkmod\TheDarkMod*.exe
      7z a -t7z TheDarkModVR.7z ..\darkmod\*.dll
      7z a -t7z TheDarkModVR.7z tdm_vr.pk4

  artifacts:
  - path: TheDarkModVR.7z
    name: TheDarkModVR

  deploy:
    provider: GitHub
    description: 'The Dark Mod VR'
    auth_token:
      secure: jMupWwNFaEHDNRvaZX4pxtGeLa9LpAK68sdQgBoUgki2JdEdRjms7irbi1PDHbKo
    artifact: 'TheDarkModVR'
    draft: true
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true

- matrix:
    only:
    - image: Ubuntu1804

  install:
  - sh: |
      sudo apt-get update && sudo apt-get -y install mesa-common-dev libxxf86vm-dev libxext-dev

  build_script:
  - sh: |
      mkdir ../darkmod
      mkdir build
      cd build
      cmake .. -DCMAKE_BUILD_TYPE="${CONFIGURATION}" -DCOPY_EXE=ON
      make -j6

  after_build:
  - sh: |
      cd ..
      CURPATH=`pwd`
      cd ../darkmod
      7za a -tzip tdm_vr.pk4 glprogs_vr
      tar -cSvf thedarkmodvr.tar "thedarkmodvr.x64" "tdm_vr.pk4" "libopenvr_api.so" "libopenxr_loader.so.1"
      bzip2 thedarkmodvr.tar
      cd $CURPATH
      mv ../darkmod/thedarkmodvr.tar.bz2 .

  artifacts:
  - path: thedarkmodvr.tar.bz2
    name: TheDarkModVRLinux
    
  deploy:
    provider: GitHub
    description: 'The Dark Mod VR'
    auth_token:
      secure: jMupWwNFaEHDNRvaZX4pxtGeLa9LpAK68sdQgBoUgki2JdEdRjms7irbi1PDHbKo
    artifact: 'TheDarkModVRLinux'
    draft: true
    prerelease: true
    on:
      APPVEYOR_REPO_TAG: true
