stages:
  - lib_build
  - cleanup_build
build_job:
  stage: lib_build
  script:
  - qmake SubParser.pro -r -spec  linux-g++-32 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make
cleanup_build_job:
  stage: cleanup_build
  script:
  - qmake SubParser.pro -r -spec  linux-g++-32 "CONFIG+=debug" "CONFIG+=qml_debug" "CONFIG+=c++11" "CONFIG += warn_off"
  - make clean
  when: on_failure